import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Start learning  by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <Link href='/posts/all-posts'>All Post</Link>

          {/* <Link href='/posts/first-post'>View First Post</Link> */}
          <Link href='/posts/1'>View First Post</Link>
          <Link href='/posts/2'>View Second Post</Link>


          <Link href='/profile/user'>View User Profile</Link>


        </div>






      </main>
    </>
  )
}
